### ISSUE TITLE
Wait loops not handling all terminal states

### ISSUE THREAD

**Issue by physcx** [awslabs/amazon-lookout-for-vision-python-sdk#1] opened 2021-04-08 12:14 UTC
https://github.com/awslabs/amazon-lookout-for-vision-python-sdk/blob/b11070f41d97e286d338191c90312d875fa54644/lookoutvision/lookoutvision.py#L272-L290

When calling create_datasets, the dataset creation is asynchronous and can succeed or fail depending on validation and format of the input manifests. The polling loop should be querying for either CREATE_COMPLETE or CREATE_FAILED as terminal states but currently is only checking for CREATE_COMPLETE. The describe_dataset reponse should provide a reason for failure in the status message.

https://github.com/awslabs/amazon-lookout-for-vision-python-sdk/blob/b11070f41d97e286d338191c90312d875fa54644/lookoutvision/lookoutvision.py#L338-L345

When calling fit, the model creation wait loop is waiting on the TRAINING state instead of waiting on the terminal states TRAINED and TRAINING_FAILED. It is important to always wait on the terminal states and not on an in progress state as services will sometimes expand the set of in progress states. For example today creating a model puts the state into TRAINING -> TRAINED|TRAINING_FAILED but in the future this could potentially be QUEUED->TRAINING->OPTIMIZING->TRAINED|TRAINING_FAILED. The set of terminal states should remain fixed.

https://github.com/awslabs/amazon-lookout-for-vision-python-sdk/blob/b11070f41d97e286d338191c90312d875fa54644/lookoutvision/lookoutvision.py#L404

Same issue for hosting, should be checking for HOSTED | HOSTING_FAILED

**Comment by pespila** [comment] 2021-04-24 13:37
Hi, thanks for reporting this issue. We appreciate your contribution! We will take a look and get back to you as soon as possible.

**Comment by pespila** [comment] 2021-07-02 07:11
Hi, the issue is now fixed and some other minor fixes are applied, too.

**Closed by pespila** 2021-07-02 07:11 UTC
